### ISSUE TITLE
TornadoVM gets stuck during sketch compilation in static context

### ISSUE THREAD

**Issue by gigiblender** [beehive-lab/TornadoVM#86]
**Describe the bug**

Creating a `TaskSchedule` and `Task` in a static block (during `clinit`) can cause TornadoVM to get stuck. This will happen if the method passed to the task will have a non-inlined callee (`invokestatic` bytecode). 

**How To Reproduce**

Run the code provided with the compiler flag `-XX:CompileCommand="dontinline Main *"`

```
public class Main {

    public static void iNeedAnInvokeStaticBytecode() {
    }

    public static void testMethod(int[] in) {
        iNeedAnInvokeStaticBytecode();
    }

    static int[] inTor = new int[] { 0 };
    static TaskSchedule ts = new TaskSchedule("s0");
    static {
        ts.task("t0", Main::testMethod, inTor);
    }

    public static void main(String[] args) {
        ts.execute();
    }
}
```
I tested the code and it seems to happen with both JDK 8 & 11 -- have not tested on other versions.

The sketch compilation for the task method (`testMethod`) gets stuck during bytecode parsing, inside JVMCI.

![image](https://user-images.githubusercontent.com/7903443/114565230-fa9c2100-9c68-11eb-8d1d-c789b2717bd2.png)

**Comment by jjfumero** [comment]
@gigiblender ., can you confirm this is now solved?

**Comment by gigiblender** [comment]
@jjfumero I have not worked on this issue since reporting it. I think this is not solved yet, unless another patch accidentally fixed it.

**Comment by gigiblender** [comment]
The issue is caused by a deadlock between the main java thread calling the class initializer `<clinit>` and the Tornado sketch compilation thread waiting for the `<clinit>` to finish. The following happens:
1) The main Java thread runs the class initializer `<clinit>` and therefore creates the Tornado task `t0`
2) A sketch compilation request is created and executed by a different thread, using the internal Tornado Executor.
3) During graph building, an `invokestatic` bytecode is parsed and because eager initialization is enabled in the bytecode parser, another class initialization is triggered on the compilation thread. 
4) The runtime checks if another class initialization of the same class is ongoing, and if it is, parks the current thread. In this case, the main thread running `<clinit>` will wait for the compilation thread to finish, but the compilation thread will not proceed until class initialization (`<clinit>`) is done. 

The deadlock issue can be solved by disabling eager initialization in the bytecode parser for all backends. This is done in the `PTX/OCLSuitedProvider::createGraphBuilderSuite` method. 

However, Tornado is still unable to compile the method above. The reason for this is that the `BytecodeParser` will insert a `DeoptimizeNode` if an `invokestatic` bytecode of a class not initialized is parsed. This will retrigger the compilation later when the class has been initialized.

![image](https://user-images.githubusercontent.com/7903443/139929802-5b17d2bf-3137-4448-8bca-d04b7a2cb9da.png)

As discussed, a solution to this second issue, would be to trigger the sketch compilation lazily during task schedule execution instead of task definition. Usually, task schedule execution does not happen during class initialization.
